const assert=require('node:assert/strict'),path=require('node:path'),fs=require('node:fs');
const {open}=require('./browser-helpers.cjs');const output=process.env.TEST_OUTPUT||path.resolve('test-output');fs.mkdirSync(output,{recursive:true});
(async()=>{
 const{browser,server,url}=await open();const page=await browser.newPage({viewport:{width:390,height:844},deviceScaleFactor:2,hasTouch:true,isMobile:true});const errors=[];page.on('pageerror',e=>errors.push(e.message));
 try{
  await page.goto(url);await page.waitForFunction(()=>window.GameDebug&&GameDebug.renderer.ready);await page.evaluate(()=>document.fonts.ready);await page.waitForTimeout(300);assert.equal(await page.evaluate(()=>GameDebug.renderer.stats.webgl),true);
  await page.screenshot({path:path.join(output,'blindfire-v0.3-menu.png')});await page.locator('#openGuide').click();assert.equal(await page.locator('.guide-list li').count(),7);await page.locator('#guideClose').click();
  await page.locator('#startAI').click();await page.evaluate(()=>{GameDebug.engine.mode='lan';GameDebug.engine.countdown=0;});await page.waitForFunction(()=>GameDebug.view.started);assert.equal(await page.evaluate(()=>GameDebug.view.enemy),null);assert.equal(await page.evaluate(()=>GameDebug.renderer.enemyTruck.visible),false);assert.equal(await page.evaluate(()=>GameDebug.renderer.cameraKey),'truck');
  const initial=await page.evaluate(()=>({x:GameDebug.view.own.x,z:GameDebug.view.own.z})),j=await page.locator('#joystick').boundingBox();await page.mouse.move(j.x+j.width/2,j.y+j.height/2);await page.mouse.down();await page.mouse.move(j.x+j.width/2+20,j.y+15);await page.waitForTimeout(350);assert.ok(await page.evaluate(()=>GameDebug.view.own.speed>1));await page.mouse.up();await page.waitForFunction(()=>Math.abs(GameDebug.view.own.speed)<1);const moved=await page.evaluate(()=>({x:GameDebug.view.own.x,z:GameDebug.view.own.z}));assert.ok(Math.hypot(moved.x-initial.x,moved.z-initial.z)>1);
  const yaw=await page.evaluate(()=>GameDebug.view.own.aim.missile.yaw);await page.mouse.move(275,330);await page.mouse.down();await page.mouse.move(335,310,{steps:4});await page.mouse.up();await page.waitForTimeout(140);assert.ok(Math.abs(await page.evaluate(()=>GameDebug.view.own.aim.missile.yaw)-yaw)>.2);
  await page.locator('[data-weapon="artillery"]').click();await page.waitForFunction(()=>GameDebug.renderer.arc.visible);assert.equal(await page.locator('#ballisticPanel').isVisible(),true);await page.locator('#fireButton').click();await page.waitForFunction(()=>GameDebug.view.own.cd.artillery>0);assert.ok(await page.evaluate(()=>GameDebug.engine.shots.some(s=>s.kind==='artillery')));
  await page.locator('#pauseButton').click();const before=await page.evaluate(()=>GameDebug.engine.t);await page.waitForTimeout(180);assert.equal(await page.evaluate(()=>GameDebug.engine.t),before);await page.locator('#pauseGuide').click();await page.locator('#guideClose').click();await page.locator('#resume').click();
  await page.locator('[data-weapon="missile"]').click();await page.locator('#fireButton').click();await page.waitForFunction(()=>GameDebug.view.own.pilot&&GameDebug.renderer.cameraKey.startsWith('flight'));assert.equal(await page.evaluate(()=>GameDebug.view.shots.find(s=>s.id===GameDebug.view.own.pilot).kind),'missile');const missile=await page.evaluate(()=>GameDebug.view.own.pilot);await page.locator('#returnVehicle').click();await page.waitForFunction(()=>GameDebug.view.own.pilot===null&&GameDebug.renderer.cameraKey==='truck');assert.ok(await page.evaluate(id=>GameDebug.view.shots.some(s=>s.id===id),missile));
  await page.locator('[data-weapon="uav"]').click();await page.locator('#fireButton').click();await page.waitForFunction(()=>GameDebug.view.shots.some(s=>s.id===GameDebug.view.own.pilot&&s.kind==='uav'));await page.locator('#returnVehicle').click();await page.waitForSelector('#takeUAV');await page.locator('#takeUAV').click();await page.waitForFunction(()=>GameDebug.view.own.pilot!==null);await page.locator('#returnVehicle').click();
  await page.evaluate(()=>{const e=GameDebug.engine,p=e.players[0];e.command(1,{type:'vehicle'});e.command(1,{type:'select',weapon:'uav'});const r=e.command(1,{type:'fire'}),q=e.shots.find(s=>s.id===r.id);Object.assign(q,{x:p.x+50,y:p.y+75,z:p.z+(p.z>400?-180:180),speed:30,pitch:0});});
  await page.locator('[data-weapon="sam"]').click();await page.locator('#fireButton').click();await page.waitForFunction(()=>GameDebug.view.own.cd.sam>20&&GameDebug.view.own.pilot===null&&GameDebug.renderer.cameraKey==='truck');assert.equal(await page.locator('#returnVehicle').isVisible(),false);assert.equal(await page.locator('#fireSub').textContent(),'自动锁定');await page.waitForFunction(()=>GameDebug.view.own.stats.intercepted>0);
  await page.locator('[data-weapon="mg"]').click();const f=await page.locator('#fireButton').boundingBox();await page.mouse.move(f.x+f.width/2,f.y+f.height/2);await page.mouse.down();await page.waitForTimeout(350);assert.equal(await page.evaluate(()=>GameDebug.view.own.mg),true);assert.ok(await page.evaluate(()=>GameDebug.view.shots.some(s=>s.mine&&s.kind==='bullet')));await page.mouse.up();await page.waitForFunction(()=>!GameDebug.view.own.mg);
  assert.equal(await page.locator('[data-action="decoy"]').count(),0);
  // World mesh and radar marker must disappear on the same five-second deadline.
  await page.evaluate(()=>{GameDebug.start(303);const e=GameDebug.engine,B=Blindfire;e.mode='lan';e.countdown=0;for(const[p,x,z]of[[e.players[0],1000,1600],[e.players[1],1000,1350]])Object.assign(p,{x,z,y:B.terrain(x,z)});e.updateIntel();});await page.waitForFunction(()=>GameDebug.view.enemy&&GameDebug.renderer.enemyTruck.visible);
  const dot=await page.evaluate(()=>{const r=GameDebug.renderer,q=r.mapPoint(GameDebug.view.enemy),px=r.miniCtx.getImageData(Math.round(q.x),Math.round(q.y),1,1).data;return{x:q.x,y:q.y,orange:px[0]>220&&px[1]<210};});assert.equal(dot.orange,true);assert.ok(dot.x>=14&&dot.x<=214&&dot.y>=14&&dot.y<=214);
  await page.evaluate(()=>{GameDebug.engine.players[1].x=1800;GameDebug.engine.updateIntel();for(let i=0;i<540;i++)GameDebug.engine.update(1/120);});await page.waitForFunction(()=>GameDebug.view.enemy&&GameDebug.view.enemy.retained);assert.equal(await page.evaluate(()=>GameDebug.renderer.enemyTruck.visible),true);
  await page.evaluate(()=>{for(let i=0;i<90;i++)GameDebug.engine.update(1/120);});await page.waitForFunction(()=>!GameDebug.view.enemy&&!GameDebug.renderer.enemyTruck.visible&&!GameDebug.renderer.enemyMarker.visible);assert.equal(await page.evaluate(q=>{const px=GameDebug.renderer.miniCtx.getImageData(Math.round(q.x),Math.round(q.y),1,1).data;return px[0]>220&&px[1]<210;},dot),false);
  // Capture an actual rendered battle with simulated launch physics and trails.
  await page.evaluate(()=>{GameDebug.start(2026);const e=GameDebug.engine,B=Blindfire;e.mode='lan';e.countdown=0;for(const[p,x,z,yaw]of[[e.players[0],1000,1600,0],[e.players[1],1190,1390,Math.PI]]){Object.assign(p,{x,z,y:B.terrain(x,z),yaw});for(const a of Object.values(p.aim))a.yaw=yaw;}GameDebug.select('artillery');e.command(0,{type:'aim',yaw:0,pitch:.42});e.command(0,{type:'fire'});e.command(1,{type:'select',weapon:'artillery'});e.command(1,{type:'aim',yaw:Math.PI-.2,pitch:.5});e.command(1,{type:'fire'});for(let i=0;i<130;i++)e.update(1/60);});await page.waitForTimeout(140);await page.screenshot({path:path.join(output,'blindfire-v0.3-artillery.png')});
  await page.locator('[data-weapon="sam"]').click();await page.waitForTimeout(200);await page.screenshot({path:path.join(output,'blindfire-v0.3-battle.png')});await page.locator('[data-weapon="uav"]').click();await page.locator('#fireButton').click();await page.waitForTimeout(450);await page.screenshot({path:path.join(output,'blindfire-v0.3-uav.png')});
  for(const[width,height]of[[360,640],[412,915],[320,568],[768,1024]]){await page.setViewportSize({width,height});await page.waitForTimeout(100);const r=await page.evaluate(()=>{const controls=document.querySelector('.controls').getBoundingClientRect(),fire=document.querySelector('#fireButton').getBoundingClientRect(),joystick=document.querySelector('#joystick').getBoundingClientRect();return{bottom:controls.bottom,h:innerHeight,fireBottom:fire.bottom,controlsTop:controls.top,overlap:joystick.right>fire.left,overflow:document.body.scrollWidth>innerWidth};});assert.ok(r.bottom<=r.h+1);assert.ok(r.fireBottom<r.controlsTop);assert.equal(r.overlap,false);assert.equal(r.overflow,false);}
  await page.setViewportSize({width:390,height:844});await page.evaluate(()=>GameDebug.engine.finish(0,'摧毁敌方发射车'));await page.waitForSelector('#again');await page.locator('#again').click();assert.equal(await page.locator('#modal').isVisible(),false);await page.evaluate(()=>GameDebug.returnMenu());await page.locator('#openLAN').click();await page.locator('#hostRoom').click();assert.ok((await page.locator('#modalCard h3').textContent()).includes('APK'));assert.deepEqual(errors,[]);
  console.log('PASS 3D WebGL, touch driving/aiming, manual weapons / automatic SAM, chase camera, 300m intel, five-second world/radar expiry, pause, cooldown, rematch and four screen sizes');
 }finally{await browser.close();server.close();}
})().catch(e=>{console.error(e);process.exit(1)});
