const assert=require('node:assert/strict'),B=require('../app/src/main/assets/engine.js');
const tick=(e,t)=>{for(let i=0;i<t*120;i++)e.update(1/120);};
const setup=()=>{const e=new B.Engine({mode:'lan',mapId:'city',countdown:0,vehicles:['kfz_artillery','handlv_missile']});Object.assign(e.players[0],{x:1000,z:1500,y:B.terrain(1000,1500),yaw:0});Object.assign(e.players[1],{x:1000,z:500,y:B.terrain(1000,500)});return e;};
let e=setup(),p=e.players[0];assert.deepEqual(p.weapons,['artillery','reconPlane','bomber']);assert.equal(p.maxHp,100);assert.equal(B.VEHICLES.kfz_artillery.price,300);assert.equal(B.VEHICLES.longnose_artillery.hp,300);assert.equal(B.VEHICLES.longnose_artillery.price,5000);
assert.equal(e.command(0,{type:'map-aim',x:1000,z:490}).ok,false);assert.equal(e.command(0,{type:'map-aim',x:1000,z:900}).ok,true);assert.ok(B.dist(B.ballistic(p).hit,{x:1000,z:900})<1);
e.command(0,{type:'aim',yaw:.6,pitch:1});assert.equal(p.aim.artillery.yaw,p.yaw);assert.equal(e.command(0,{type:'fire'}).ok,false);tick(e,1);assert.ok(Math.abs(p.yaw-.6)<.01);assert.equal(p.aim.artillery.yaw,p.yaw);assert.equal(e.command(0,{type:'fire'}).ok,true);assert.equal(p.cd.artillery,6.5);const shell=e.shots.find(s=>s.kind==='artillery');Object.assign(shell,{x:e.players[1].x,y:e.players[1].y+2,z:e.players[1].z});e.explode(shell,true);assert.equal(e.players[1].hp,20);
e=setup();p=e.players[0];e.command(0,{type:'select',weapon:'reconPlane'});e.command(0,{type:'aim',yaw:0,pitch:0});assert.equal(e.command(0,{type:'fire'}).ok,true);assert.equal(p.pilot,null);assert.equal(p.cd.reconPlane,30);let scout=e.shots.find(s=>s.kind==='reconPlane');Object.assign(scout,{x:1000,z:1001,y:350});e.updateIntel();assert.equal(e.snapshot(0).enemy,null);scout.z=999;assert.equal(e.inReconRange(0,{x:1000,z:500,y:0}),true);assert.equal(e.command(0,{type:'pilot',id:scout.id}).ok,false);const z=scout.z;tick(e,.5);assert.ok(Math.abs(scout.z-(z-50))<.01);scout.x=1900;scout.z=1900;e.updateIntel();assert.ok(e.snapshot(0).enemy.retained);tick(e,8.1);assert.equal(e.snapshot(0).enemy,null);
e=setup();p=e.players[0];e.command(0,{type:'select',weapon:'bomber'});const r=e.command(0,{type:'fire'});assert.ok(r.ok);const plane=e.shots.find(s=>s.id===r.id);assert.equal(p.pilot,plane.id);assert.equal(p.cd.bomber,60);assert.equal(plane.speed,78);assert.equal(e.snapshot(0).shots[0].bombs,1);e.command(0,{type:'vehicle'});assert.equal(e.command(0,{type:'pilot',id:plane.id}).ok,true);const drop=e.command(0,{type:'bomb'});assert.ok(drop.ok);assert.equal(plane.bombs,0);assert.equal(e.command(0,{type:'bomb'}).ok,false);const bomb=e.shots.find(s=>s.id===drop.id),y=bomb.y;tick(e,.2);assert.ok(bomb.y<y);assert.ok(plane.y>bomb.y);Object.assign(bomb,{x:e.players[1].x,y:e.players[1].y,z:e.players[1].z});e.explode(bomb);assert.equal(e.players[1].hp,10);
for(const kind of ['reconPlane','bomber']){e=setup();const aircraft=e.launch(e.players[0],kind),defender=e.players[1];Object.assign(aircraft,{x:defender.x+80,y:defender.y+100,z:defender.z,speed:0});e.command(1,{type:'select',weapon:'sam'});assert.ok(e.command(1,{type:'fire'}).ok);tick(e,2);assert.equal(e.shots.some(s=>s.id===aircraft.id),false);assert.equal(defender.stats.intercepted,1);}
for(const difficulty of ['easy','standard','hard']){e=new B.Engine({mode:'ai',countdown:0,difficulty,vehicles:['handlv_missile','kfz_artillery']});tick(e,90);assert.ok(e.players[1].weapons.includes(e.players[1].selected));assert.ok(e.shots.every(s=>s.owner!==1||['artillery','reconPlane','bomber','bomb'].includes(s.kind)));}
console.log('PASS KFZ hull aim, distinct artillery range/cooldown/damage, flyby footprint/intel, bomber bomb separation/damage, SAM interceptions and AI loadout');
