// Exercise the production scene/camera code without requiring a WebGL driver.
import fs from 'node:fs';import assert from 'node:assert/strict';import {createRequire}from 'node:module';import * as T from '../app/src/main/assets/three.module.js';import {GLTFLoader}from '../app/src/main/assets/GLTFLoader.js';
const require=createRequire(import.meta.url);globalThis.window={};const B=require('../app/src/main/assets/engine.js');window.Blindfire=B;globalThis.innerHeight=844;globalThis.innerWidth=390;globalThis.document={getElementById:()=>null};
const {MeshoptDecoder}=await import('../app/src/main/assets/meshopt_decoder.module.js');const loader=new GLTFLoader().setMeshoptDecoder(MeshoptDecoder);loader.register(parser=>{parser.loadTexture=async()=>null;const embedded=parser.loadBuffer.bind(parser);parser.loadBuffer=async index=>{const uri=parser.json.buffers[index].uri;if(!uri)return embedded(index);const b=fs.readFileSync(new URL('../app/src/main/assets/models/'+uri,import.meta.url));return b.buffer.slice(b.byteOffset,b.byteOffset+b.byteLength);};return{name:'geometry-only-check'};});GLTFLoader.prototype.loadAsync=async path=>{const b=fs.readFileSync(new URL('../app/src/main/assets/'+path,import.meta.url));return loader.parseAsync(b.buffer.slice(b.byteOffset,b.byteOffset+b.byteLength),'');};
const {Renderer}=await import('../app/src/main/assets/render.js');const r=Object.create(Renderer.prototype);Object.assign(r,{ready:true,scene:new T.Scene(),ownTruck:new T.Group(),enemyTruck:new T.Group(),enemyMarker:new T.Group(),shadows:[new T.Group(),new T.Group()],meshes:new Map(),trailMeshes:new Map(),effectMeshes:new Map(),arc:new T.Line(new T.BufferGeometry(),new T.LineDashedMaterial()),hitRing:new T.Mesh(),landingArrow:new T.Mesh(),camera:new T.PerspectiveCamera(62,390/844,.35,8000),gl:{render(){}},landscapeMap:'city'});r.scene.add(r.ownTruck,r.enemyTruck);for(const method of ['drawMini','drawEnemyDots','drawScope','updateReticle'])r[method]=()=>{};
await r.loadVehicles();assert.ok(r.modelsReady);assert.ok(fs.statSync(new URL('../app/src/main/assets/models/kfz_grille.glb',import.meta.url)).size<5000000);const grille=r.vehicleModels[0].kfz_artillery;const dims=new T.Box3().setFromObject(grille.node).getSize(new T.Vector3());assert.ok(Math.abs(dims.x-2.16)<.001&&Math.abs(dims.y-2.4)<.001&&Math.abs(dims.z-4.84)<.001);const low=new T.Box3().setFromObject(grille.barrel);grille.barrel.rotation.x=.6;const raised=new T.Box3().setFromObject(grille.barrel);assert.ok(raised.max.y>low.max.y+.3);grille.barrel.rotation.x=0;assert.equal(grille.turret,undefined);
for(const id of Object.keys(B.VEHICLES))for(const yaw of [0,.8,Math.PI/2]){const e=new B.Engine({mode:'lan',mapId:'city',countdown:0,vehicles:[id]});const p=e.players[0];Object.assign(p,{x:1000,z:1500,y:2,yaw});for(const a of Object.values(p.aim))a.yaw=yaw;e.players[1].x=100;e.players[1].z=100;r.cameraKey=null;r.mapAim=false;r.draw(e.snapshot(0),0);const bounds=new T.Box3().setFromObject(r.ownTruck);let low=Infinity,high=-Infinity;for(const x of [bounds.min.x,bounds.max.x])for(const y of [bounds.min.y,bounds.max.y])for(const z of [bounds.min.z,bounds.max.z]){const q=new T.Vector3(x,y,z).project(r.camera);low=Math.min(low,q.y);high=Math.max(high,q.y);}const fraction=(high-low)/2;assert.ok(fraction>=.30&&fraction<=.40,`${id} yaw ${yaw} framing ${fraction}`);}
const e=new B.Engine({mode:'lan',mapId:'city',countdown:0,vehicles:['kfz_artillery']});r.mapAim=true;r.mapCenter={x:1000,z:1000};r.draw(e.snapshot(0),0);const rotation=r.camera.quaternion.clone();for(let i=0;i<20;i++){r.panMap(20,-15);r.draw(e.snapshot(0),i*.016);assert.ok(r.camera.quaternion.angleTo(rotation)<1e-7);assert.equal(r.camera.position.x,r.mapCenter.x);assert.equal(r.camera.position.z,r.mapCenter.z);}r.mapAim=false;
e.command(0,{type:'select',weapon:'bomber'});const launched=e.command(0,{type:'fire'});assert.ok(launched.ok);r.draw(e.snapshot(0),1);const planeMesh=r.meshes.get(launched.id);assert.ok(planeMesh.userData.bomb.visible);assert.ok(e.command(0,{type:'bomb'}).ok);r.draw(e.snapshot(0),1.1);assert.equal(planeMesh.userData.bomb.visible,false);assert.ok([...r.meshes.values()].some(g=>g!==planeMesh&&g.children.length>=4));
const ju=fs.readFileSync(new URL('../app/src/main/assets/models/ju87_redtail.glb',import.meta.url)),doc=JSON.parse(ju.subarray(20,20+ju.readUInt32LE(12)));assert.ok(doc.extras.paintedMaterialIds.length);for(const id of doc.extras.paintedMaterialIds){const material=doc.materials[id];assert.deepEqual(material.pbrMetallicRoughness.baseColorFactor,[1,0,0,1]);assert.equal(material.pbrMetallicRoughness.baseColorTexture,undefined);}
console.log('PASS real model loading and KFZ dimensions/barrel pitch, all vehicle chase framing 30–40%, map drag stable north, bomber visual bomb separation and solid red materials');

for(const id of ['kfz_artillery','b_tank']){const asset=r.vehicleModels[0][id];assert.ok(asset.wheels.length>=10,`${id} wheel count ${asset.wheels.length}`);assert.ok(asset.tracks.belts.length>=2);const original=asset.tracks.belts.map(b=>Array.from(b.mesh.geometry.attributes.position.array));const e=new B.Engine({mode:'lan',countdown:0,vehicles:[id]});const p=e.players[0];p.trackTravel={left:0,right:0};r.switchVehicle(r.ownTruck,0,id);r.updateTruck(r.ownTruck,p,p.selected,0);asset.tracks.belts.forEach((b,i)=>assert.deepEqual(Array.from(b.mesh.geometry.attributes.position.array),original[i]));p.wheelTravel=2;p.trackTravel={left:2.4,right:1.6};r.updateTruck(r.ownTruck,p,p.selected,1);assert.ok(asset.wheels.every(w=>Math.abs(w.pivot.rotation.x)>.1));assert.ok(asset.tracks.belts.some((b,i)=>Array.from(b.mesh.geometry.attributes.position.array).some((v,j)=>Math.abs(v-original[i][j])>.001)));console.log(id,'wheels',asset.wheels.length,'belts',asset.tracks.belts.length);}
const tank=r.vehicleModels[0].b_tank,p=new B.Engine({mode:'lan',vehicles:['b_tank']}).players[0];p.aim.autocannon={yaw:p.yaw+.7,pitch:.2};r.switchVehicle(r.ownTruck,0,'b_tank');r.updateTruck(r.ownTruck,p,'autocannon',1);assert.ok(Math.abs(tank.turret.rotation.y+.7)<1e-8);assert.equal(tank.barrel.rotation.x,-.2);r.updateTruck(r.ownTruck,p,'repair',1);assert.equal(tank.barrel.rotation.x,-.2);assert.ok(tank.barrel.children.length>0);console.log('PASS KFZ and B tank original tread geometry preserved at rest, tracks/wheels roll, turret yaw/barrel elevation persist while using support abilities');
