const assert=require('node:assert/strict'),B=require('../app/src/main/assets/engine.js'),{Progress,KEY}=require('../app/src/main/assets/progress.js');
const tick=(e,t)=>{for(let i=0;i<Math.ceil(t/.01);i++)e.update(.01);};
const setup=(id='b_tank')=>{const e=new B.Engine({mode:'lan',mapId:'city',countdown:0,vehicles:[id,'longnose_artillery']});Object.assign(e.players[0],{x:1000,z:1000,y:2,yaw:0});for(const a of Object.values(e.players[0].aim))a.yaw=0;Object.assign(e.players[1],{x:1500,z:1000,y:2});return e;};
let e=setup(),p=e.players[0];assert.equal(p.hp,150);assert.equal(B.VEHICLES.b_tank.price,200);assert.equal(B.VEHICLES.b_tank.speed,39);assert.equal(B.VEHICLES.b_tank.recon,200);assert.equal(B.VEHICLES.b_tank.intelLife,5);
e.damage(p,1,9.99);assert.equal(p.hp,150);e.damage(p,1,10);assert.equal(p.hp,140);
for(let i=0;i<10;i++){assert.ok(e.command(0,{type:'fire'}).ok);assert.equal(e.command(0,{type:'fire'}).ok,false);if(i<9)tick(e,.41);}assert.equal(p.ammo,0);assert.ok(e.snapshot(0).own.reloadLeft>4.9);assert.equal(e.command(0,{type:'fire'}).ok,false);tick(e,4.8);assert.equal(p.ammo,0);tick(e,.21);assert.equal(p.ammo,10);assert.ok(e.command(0,{type:'fire'}).ok);
e=setup();p=e.players[0];p.hp=25;p.speed=30;e.command(0,{type:'select',weapon:'repair'});assert.ok(e.command(0,{type:'fire'}).ok);const pose=[p.x,p.z,p.yaw];assert.equal(p.speed,0);assert.equal(e.command(0,{type:'control',throttle:1,steer:1}).ok,false);e.command(0,{type:'select',weapon:'autocannon'});assert.equal(e.command(0,{type:'fire'}).ok,false);tick(e,14.9);assert.equal(p.hp,25);assert.deepEqual([p.x,p.z,p.yaw],pose);tick(e,.12);assert.equal(p.hp,150);e.command(0,{type:'select',weapon:'repair'});p.hp=100;assert.equal(e.command(0,{type:'fire'}).ok,false);
e=setup();p=e.players[0];e.command(0,{type:'select',weapon:'observation'});assert.ok(e.command(0,{type:'fire'}).ok);assert.ok(e.inReconRange(0,{x:1000,y:2,z:501}));assert.equal(e.inReconRange(0,{x:1501,y:2,z:1000}),false);assert.equal(e.inReconRange(0,{x:1000,y:2,z:1499}),false);assert.equal(e.command(0,{type:'fire'}).ok,false);tick(e,8.1);assert.equal(e.inReconRange(0,{x:1000,y:2,z:501}),false);tick(e,7);assert.ok(e.command(0,{type:'fire'}).ok);
for(const id of ['longnose_artillery','kfz_artillery']){e=setup(id);p=e.players[0];e.command(0,{type:'artillery-mode',mode:'direct'});e.command(0,{type:'aim',yaw:0,pitch:-2});assert.equal(p.aim.artillery.pitch,-3*Math.PI/180);e.command(0,{type:'artillery-mode',mode:'curve'});e.command(0,{type:'aim',yaw:0,pitch:2});assert.equal(p.aim.artillery.pitch,B.VEHICLES[id].maxPitch);const r=B.artilleryRanges(p);assert.ok(r.minCurve>500&&r.minCurve<r.max);assert.equal(e.command(0,{type:'map-aim',x:1000,z:900}).ok,false);const target={x:1000,z:1000-r.minCurve-30};assert.ok(e.command(0,{type:'map-aim',...target}).ok);const arc=B.ballistic(p);assert.ok(arc.hit);assert.ok(B.dist(arc.hit,target)<1);}
assert.equal(B.WEAPONS.bomber.speed,78);assert.equal(B.VEHICLES.longnose_artillery.hp,300);assert.equal(B.weaponSpec({vehicleId:'longnose_artillery'},'artillery').directDamage,260);assert.equal(B.weaponSpec({vehicleId:'longnose_artillery'},'uav').directDamage,80);assert.equal(B.weaponSpec({vehicleId:'handlv_missile'},'uav').directDamage,30);
for(const kind of ['missile','uav','artillery','autocannon','bullet','sam']){e=setup(kind==='artillery'?'longnose_artillery':kind==='autocannon'?'b_tank':'handlv_missile');p=e.players[0];const q=e.launch(e.players[1],'bomber');Object.assign(q,{x:900,y:100,z:900,hp:200,speed:0});let s;if(kind==='bullet'){p.aim.mg={yaw:0,pitch:0};e.shootMG(p);s=e.shots.at(-1);}else s=e.launch(p,kind);Object.assign(s,{x:910,y:100,z:900});const before=q.hp;e.intercept(s,{x:890,y:100,z:900});assert.ok(q.hp<before,`${kind} did not hit airborne target`);assert.equal(s.hp,0);}
e=setup('longnose_artillery');const centered=e.launch(e.players[0],'artillery');Object.assign(centered,{x:e.players[1].x,y:e.players[1].y,z:e.players[1].z});e.explode(centered);assert.equal(e.players[1].hp,40);
// Air splash damage and projectile range clipping.
e=setup('longnose_artillery');const q=e.launch(e.players[1],'bomber');Object.assign(q,{x:1000,y:100,z:1000,hp:45});const shell=e.launch(e.players[0],'artillery');Object.assign(shell,{x:1001,y:100,z:1000});e.explode(shell);assert.ok(q.hp<=0);assert.equal(e.players[0].stats.intercepted,1);
e=setup();p=e.players[0];const shot=e.launch(p,'autocannon');Object.assign(shot,{x:1000,y:100,z:1000,vx:720,vy:0,vz:0,distance:490});e.update(.05);assert.equal(shot.hp,0);assert.ok(shot.x<=1010.000001);
for(const id of Object.keys(B.VEHICLES))for(let seed=1;seed<=20;seed++){const m=new B.Engine({mode:'ai',vehicles:[id],seed});assert.ok(Math.abs(B.vehicleSpec(m.players[1].vehicleId).tier-B.vehicleSpec(id).tier)<=1);assert.ok(B.matchCandidates(id).includes(m.players[1].vehicleId));}
const values=new Map(),storage={getItem:k=>values.get(k)||null,setItem:(k,v)=>values.set(k,v)},profile=new Progress(storage);profile.coins=6000;assert.equal(profile.purchase('longnose_artillery'),false);profile.research.artillery=2500;assert.ok(profile.researchVehicle('longnose_artillery'));assert.ok(profile.purchase('longnose_artillery'));assert.equal(profile.research.artillery,0);
const reward=profile.reward('battle','win',{vehicleId:'b_tank',roomTier:2,stats:{damage:100,intercepted:1,detections:2}});assert.ok(reward>100);assert.ok(profile.lastResearch>40);assert.equal(profile.research.missile,0);assert.equal(profile.research.artillery,0);assert.equal(profile.reward('battle','win',{vehicleId:'b_tank'}),0);const restored=new Progress(storage);assert.equal(restored.research.tank,profile.research.tank);assert.ok(restored.owned.includes('longnose_artillery'));
values.set(KEY,JSON.stringify({version:1,coins:123,owned:['longnose_artillery'],selected:'longnose_artillery'}));const legacy=new Progress(storage);assert.equal(legacy.coins,123);assert.ok(legacy.researched.includes('longnose_artillery'));assert.equal(legacy.selected,'longnose_artillery');
for(const difficulty of ['easy','standard','hard']){e=new B.Engine({mode:'ai',countdown:0,difficulty,vehicles:['handlv_missile','b_tank'],seed:12});tick(e,45);assert.ok(e.players[1].weapons.includes(e.players[1].selected));}
console.log('PASS B tank magazine/reload, immunity, stationary single-use repair, sector scan; gun limits/map rejection, airborne hits/splash, range clipping, tier matching, separate research/rewards and legacy save migration');
